"""Deterministic detection of explicit AI-attribution signals in commits."""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any

import pandas as pd


@dataclass(frozen=True)
class Attribution:
    """An observable attribution signal, not a claim about code provenance."""

    tool: str
    evidence_type: str
    signal: str


COMMIT_RULES: tuple[tuple[str, str, str, re.Pattern[str]], ...] = (
    ("claude_code", "auto_declaration", "author_email", re.compile(r"noreply@anthropic\.com", re.I)),
    ("claude_code", "auto_declaration", "message", re.compile(r"co-authored-by:\s*claude|generated with claude code", re.I)),
    ("copilot", "auto_declaration", "message", re.compile(r"co-authored-by:\s*copilot\b", re.I)),
    ("aider", "auto_declaration", "author_name", re.compile(r"\(aider\)", re.I)),
    ("aider", "auto_declaration", "message", re.compile(r"^aider:", re.I)),
    ("replit", "auto_declaration", "message", re.compile(r"generated by replit|replit-commit-author:", re.I)),
    ("devin", "structurelle", "author_email", re.compile(r"devin-ai-integration", re.I)),
)


def detect_commit_attribution(record: dict[str, Any] | pd.Series) -> Attribution | None:
    """Return the first explicit AI attribution observed on a commit record."""
    for tool, evidence_type, field, pattern in COMMIT_RULES:
        value = str(record.get(field, "") or "")
        if pattern.search(value):
            return Attribution(tool=tool, evidence_type=evidence_type, signal=field)
    return None


def tag_commits(commits: pd.DataFrame) -> pd.DataFrame:
    """Add explicit-attribution columns without inferring the origin of code."""
    result = commits.copy()
    detected = result.apply(detect_commit_attribution, axis=1)
    result["ai_attribue"] = detected.notna()
    result["outil"] = detected.map(lambda item: item.tool if item else None)
    result["type_preuve"] = detected.map(lambda item: item.evidence_type if item else None)
    result["signal_attribution"] = detected.map(lambda item: item.signal if item else None)
    return result
