"""Deterministic discovery and classification of AI disclosure policies."""

from __future__ import annotations

import base64
import re


CANDIDATE_PATHS = (
    "CONTRIBUTING.md", ".github/CONTRIBUTING.md", "docs/CONTRIBUTING.md",
    ".github/PULL_REQUEST_TEMPLATE.md", "AI_POLICY.md", ".github/ai-policy.md",
)
AI_MENTION = re.compile(r"\b(ai[- ]generated|generated by (ai|copilot|chatgpt|claude|gemini)|g[ée]n[ée]r[ée] par (l'ia|ia|ai)|copilot|chatgpt|llm|large language model)\b", re.I)
OBLIGATION = re.compile(r"\b(must|required|mandatory|shall|doit|obligatoire|requis)\b", re.I)
RECOMMENDATION = re.compile(r"\b(should|please|encouraged|recommended|recommand|merci de|veuillez)\b", re.I)


def classify_policy(text: str, window: int = 200) -> dict[str, bool | str]:
    """Classify nearby normative language around an explicit AI mention."""
    matches = list(AI_MENTION.finditer(text))
    if not matches:
        return {"mention_ia": False, "niveau": "aucune_mention"}
    level = "mention_sans_regle"
    for match in matches:
        context = text[max(0, match.start() - window):match.end() + window]
        if OBLIGATION.search(context):
            return {"mention_ia": True, "niveau": "obligatoire"}
        if RECOMMENDATION.search(context):
            level = "recommandee"
    return {"mention_ia": True, "niveau": level}


def find_policy_files(owner: str, repo: str, headers: dict[str, str]) -> dict[str, str]:
    """Fetch existing candidate files from GitHub's contents API."""
    try:
        import requests
    except ImportError as error:
        raise RuntimeError("Install collection dependencies with: pip install -e '.[collect]'") from error
    found: dict[str, str] = {}
    for path in CANDIDATE_PATHS:
        response = requests.get(f"https://api.github.com/repos/{owner}/{repo}/contents/{path}", headers=headers, timeout=30)
        if response.status_code != 200:
            continue
        content = response.json().get("content", "")
        found[path] = base64.b64decode(content).decode("utf-8", errors="replace")
    return found